name: Generate SBOM (CI/CD)

on:
  push:
    branches: [ "main" ]

jobs:
  sbom-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 這裡是最重要的修改：明確指定 requirements.txt
      - name: Run Syft to generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: requirements.txt       # 指定掃描這個檔案
          format: cyclonedx-json
          output-file: github_sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SBOM-Report
          path: github_sbom.json
          retention-days: 5